//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;

    public partial class OrderPro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderPro()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.OrderStatusLogs = new HashSet<OrderStatusLog>();
        }

        public int ID { get; set; }
        public System.DateTime DateOrder { get; set; }
        public int IDCus { get; set; }
        public string AddressDelivery { get; set; }
        public string StatusOrder { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<int> VoucherID { get; set; }
        public string Note { get; set; }
        public string Name { get; set; }

        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Voucher Voucher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderStatusLog> OrderStatusLogs { get; set; }
    }
}
