//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReview
    {
        public int ReviewID { get; set; }
        public int IDCus { get; set; }
        public int ProductID { get; set; }
        public string ReviewText { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public string AdminResponse { get; set; }
        public int Rating { get; set; } // 1-5 sao
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
