//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevenueReport
    {
        public int ReportID { get; set; }
        public int ReportMonth { get; set; }
        public int ReportYear { get; set; }
        public decimal TotalRevenue { get; set; }
        public int TotalOrders { get; set; }
        public string TopCustomer { get; set; }
        public string TopProduct { get; set; }
        public int? TopCustomerID { get; set; }
        public int? TopProductID { get; set; }

        public Nullable<System.DateTime> GeneratedAt { get; set; }
    }
}
